server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webhacking?serverTimezone=Asia/Seoul
    username: root
    password: 1107jkk!
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


mybatis:
  type-aliases-package: wrsungspringsecurity.vo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mapper/*.xml

logging:
  level:
    org:
      apache:
        ibatis: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE